##
# Project Title
#
# @file
# @version 0.1

build_one:
	gcc problem_one.c -o problem_one -Wall -g

build_two:
	gcc problem_two.c -o problem_two -Wall -g

build_three:
	gcc problem_three.c -o problem_three -Wall -g


# end
