##
# Project Title
#
# @file
# @version 0.1
build:
	gcc main.c -o run1 -Wall -g

prob2:
	gcc prob2.c -o run2 -Wall -g

prob3:
	gcc prob3.c -o run3 -Wall -g

prob4:
	gcc prob4.c -o run4 -Wall -g

clean:
	rm run*
# end
